local-data: "global.handler.control.privatelink.monitor.azure.com. CNAME amcs-prod-global-handler.trafficmanager.net."
local-data: "canadacentral-1.in.ai.privatelink.monitor.azure.com. CNAME gig-ai-prod-canadacentral-0.trafficmanager.net."
