#!/bin/sh

# rotate the latest log file

PATH=/usr/local/bin:/usr/local/sbin:/bin:/usr/bin:/usr/sbin

LOGD=/var/unbound/var/log
LOGF=unbound
MAX=50000000

# TSTAMP=`echo | tai64n`
TSTAMP=`python3 -c 'import time; print(int(round(time.time() * 1000)))'`

cd $LOGD
SZ=`stat $LOGF| cut -d' ' -f8`
if [ -s unbound -a $SZ -gt $MAX ]; then
	mv unbound $TSTAMP
	unbound-control log_reopen
	gzip $TSTAMP
fi
