#!/usr/bin/env python3

import io
import sys
from pathlib import Path

'''

generate the dnsdist jinga configuration file

-- These are comments

Here are the data types:
    Server: generated with newServer()
    ComboAddress: represents an IP address and Port
    DNSName: represents a FQDN
    Netmask: represents a netmask or network
    NetmaskGroup: represents a group of netmasks
    SuffixMatchNode: represents a group of domain suffixes for fast searching
    DNSHeader: a header of a DNS packet
    ClientState: the addresses and ports that dnsdist is listening on

'''

DnsDistDir = '/etc/dnsdist'
ReadDnsDistDir = '/home/ansible/systems/files/dnsdist'
GlobalAcl = 'global.acl'
AzureAcl = 'on-prem-azure-nets'
AzurePrivZones = 'azure-priv-zones'
AzurePubZones = 'azure-pub-zones'
QACloudZones = 'qa-cloud-utoronto-ca-zones'
PRODCloudZones = 'prod-cloud-utoronto-ca-zones'
LocalZones = 'local-zones'
LocalZones = 'forward.zones'
ArpaZones = 'arpa.zones'
TypoZones = 'typo.zones'

Ans1 = '128.100.235.12'
Ans2 = '128.100.213.12'
LocalHost = '127.0.0.1'
Dns1 = '128.100.100.128'
Dns1Resolver = '128.100.100.129'
Dns4 = '128.100.56.135'
Dns4Resolver = '128.100.56.130'
Dns5 = '128.100.96.34'
Dns5Resolver = '128.100.96.36'

Cira1 = '149.112.121.10'
Cira2 = '149.112.122.10'
CloudF = '1.1.1.1'
Four9s = '9.9.9.9'
Google1 = '8.8.8.8'
Google2 = '8.8.4.4'

MyIp = Dns4

LocalPort = 5353
Port = 53
ControlPort = 5333
WebPort = 8088

EISNet = '128.100.102.0/23'
SafeNets = '{\'127.0.0.1/8\', \'128.100.56.128/27\', \'128.100.96.32/29\', \'128.100.102.0/23\'}'
DefServer = {'128.100.96.34': 'dns5'}

'''
        'dns4pdnsreolver': Dns4Resolver,
        'cloudflare': CloudF,
        '4nines': Four9s,
'''

Pools = {
    'cira': {
        'cira1': Cira1,
        'cira2': Cira2,
    },
    'bluecat': {
        'ans1': Ans1,
        'ans2': Ans2,
    },
    'azure_prod': {
        'prod1': '142.1.78.12',
        'prod2': '142.1.78.13',
        'prod3': '142.1.78.14',
        'prod4': '142.1.78.15',
    },
    'azure_qa': {
        'qa1': '142.150.247.12',
        'qa2': '142.150.247.13',
        'qa3': '142.150.247.14',
        'qa4': '142.150.247.15',
    },
    'typo': {'blackhole': '128.100.100.130'},
}

WebPw = 'John1717'
ApiKey = 'fichoo2Choh8'

CacheSize = 100000

#    print(f'includeDirectory("{DnsDistDir}")')

def jinga_header():
    print("""
{# This jinga template for dnsdist.conf is autogenerated. Do NOT edit #}
{# See ~/systems/files/dnsdist/gen-dnsdist-conf-jinga.py #}
{% set os = ansible_facts['distribution'] %}
{% set os_ver = ansible_facts['distribution_version'] %}
{% set hname = inventory_hostname %}
{% set primary_ip = ansible_facts['all_ipv4_addresses'][0] %}
{% set secondary_ip = ansible_facts['all_ipv4_addresses'][0] %}
{% if dnsdist_testing[hname]  %}
{% set ext_ip = secondary_ip %}
{% set int_ip = primary_ip %}
{% else %}
{% set ext_ip = primary_ip %}
{% set int_ip = secondary_ip %}
{% endif %}
{% set pools = dnsdist_data[hname]['pools'] %}
    """)

def glob():
    print('-- Listen Sockets')
    print(f'setLocal("{LocalHost}:{LocalPort}")')
    print(f'addLocal("{{{{ ext_ip }}}}:{Port}")')

    print("\n-- Control Socket, Console and Webserver")
    print(f"controlSocket('{LocalHost}:{ControlPort}')")
    print("setKey('QfhaEHPbEM+zPBR1tQe6K6pceGorSbqxZLoZtFrcPLw=')")
    print(f"setConsoleACL({SafeNets})")

    print(f'webserver("{{{{ primary_ip }}}}:{WebPort}")')
    print(f"setWebserverConfig({{password='{WebPw}', apiKey='{ApiKey}', acl='{EISNet}'}})")

    print("\n-- Access Control Lists")
    print(f"setACLFromFile('{DnsDistDir}/{GlobalAcl}')")

def servers():
    print("\n-- Pools")
    print("""
{% for nm, ip in pools['default'].items() %}
newServer({ name='{{nm}}', address='{{ip}}', pool='' })
{% endfor %}

{% for nm, ip in pools['local'].items() %}
newServer({ name='{{nm}}', address='{{ip}}', pool='local' })
{% endfor %}
    """)
    for pool in Pools:
        pdict = Pools[pool]
#        print(f"setPoolServerPolicy(roundrobin, '{pool}')")
        for srv in pdict:
            print(f"newServer({{name='{srv}', address='{pdict[srv]}', pool='{pool}'}})")
    print("\n-- Packet Caches")
    print(f"pc = newPacketCache({CacheSize})")
    print("getPool(''):setCache(pc)")

def dynamic_blocks():
    rate = 60
    brate = 40000
    exceed = 15
    block = 60
    print("\n-- Dynamic Blocks")
    print("local dbr = dynBlockRulesGroup()")
    print(f"dbr:setQueryRate({rate}, {exceed}, 'Exceeded query rate', {block})")
    print(f"dbr:setRCodeRate(DNSRCode.NXDOMAIN, {rate}, {exceed}, 'Exceeded NXD rate', {block})")
    print(f"dbr:setRCodeRate(DNSRCode.SERVFAIL, {rate}, {exceed}, 'Exceeded ServFail rate', {block})")
    print(f"dbr:setQTypeRate(DNSQType.ANY, {int(rate/1.5)}, {exceed}, 'Exceeded ANY rate', {block})")
    print(f"dbr:setResponseByteRate({brate}, {exceed}, 'Exceeded Byte rate', {block})") 

def net_mask_groups():
    print("\n-- NetMask Groups")
    aclf = f"{ReadDnsDistDir}/{AzureAcl}"
    print("az_nmg = newNMG()")
    lines = Path(aclf).read_text().splitlines()
    for l in lines:
        if l[0] != '#':
            print(f"az_nmg:addMask('{l}')")

def suffix_match_nodes():
    print("\n-- Suffix Match Nodes")

    azure_priv_f = f"{ReadDnsDistDir}/{AzurePrivZones}"
    azure_pub_f = f"{ReadDnsDistDir}/{AzurePubZones}"
    azure_prod_cloud_f = f"{ReadDnsDistDir}/{PRODCloudZones}"
    azure_qa_cloud_f = f"{ReadDnsDistDir}/{QACloudZones}"

    print("azure_priv_smn = newSuffixMatchNode()")
    lines = Path(azure_priv_f).read_text().splitlines()
    for l in lines:
        if l[0] != '#':
            print(f"azure_priv_smn:add('{l}')")

    print("azure_pub_smn = newSuffixMatchNode()")
    lines = Path(azure_pub_f).read_text().splitlines()
    for l in lines:
        if l[0] != '#':
            print(f"azure_pub_smn:add('{l}')")

    print("azure_prod_cloud_smn = newSuffixMatchNode()")
    lines = Path(azure_prod_cloud_f).read_text().splitlines()
    for l in lines:
        if l[0] != '#':
            print(f"azure_prod_cloud_smn:add('{l}')")

    print("azure_qa_cloud_smn = newSuffixMatchNode()")
    lines = Path(azure_qa_cloud_f).read_text().splitlines()
    for l in lines:
        if l[0] != '#':
            print(f"azure_qa_cloud_smn:add('{l}')")

    print()
    local_names = f"{ReadDnsDistDir}/{LocalZones}"
    print("local_smn = newSuffixMatchNode()")
    lines = Path(local_names).read_text().splitlines()
    for l in lines:
        if l[0] != '#':
            print(f"local_smn:add('{l}')")

    print()
    arpa_names = f"{ReadDnsDistDir}/{ArpaZones}"
    print("arpa_smn = newSuffixMatchNode()")
    lines = Path(arpa_names).read_text().splitlines()
    for l in lines:
        if l[0] != '#':
            print(f"arpa_smn:add('{l}')")

    print()
    typo_names = f"{ReadDnsDistDir}/{TypoZones}"
    print("typo_smn = newSuffixMatchNode()")
    lines = Path(typo_names).read_text().splitlines()
    for l in lines:
        if l[0] != '#':
            print(f"typo_smn:add('{l}')")

def regex_patterns():
    digits = '[0-9]{3}'
    suffix = '[A-Z0-9_-]+'
    ams = '[DQS]301AMD'
    prod = '[NP]'
    qa = '[DQS]'
    dot = '\\\.'
    ams_pre = f'{ams}{suffix}'
    prod_pre = f'{prod}{digits}{suffix}'
    qa_pre = f'{qa}{digits}{suffix}'
    priv = 'privatelink'
    print("\n-- Regex Rules")
    print("-- public")
    print(f"ams_prefix = RegexRule('^{ams_pre}{dot}')")
    print(f"prod_prefix = RegexRule('^{prod_pre}{dot}')")
    print(f"qa_prefix = RegexRule('^{qa_pre}{dot}')")

def selectors():
    print("\n-- Selectors")
    print("azure_net_rule = NetmaskGroupRule(az_nmg)")
    print("local_name_rule = SuffixMatchNodeRule(local_smn)")
    print("arpa_rule = SuffixMatchNodeRule(arpa_smn)")
    print("typo_rule = SuffixMatchNodeRule(typo_smn)")
    print("azure_priv_name_rule = SuffixMatchNodeRule(azure_priv_smn)")
    print("azure_pub_name_rule = SuffixMatchNodeRule(azure_pub_smn)")
    print("azure_prod_cloud_name_rule = SuffixMatchNodeRule(azure_prod_cloud_smn)")
    print("azure_qa_cloud_name_rule = SuffixMatchNodeRule(azure_qa_cloud_smn)")
    print("prod_prefix_rule = OrRule({prod_prefix, ams_prefix})")
    print("azure_prefix_rule = OrRule({prod_prefix, qa_prefix})")
    print("prod_suffix_rule = OrRule({azure_priv_name_rule, azure_prod_cloud_name_rule})")
    print("qa_suffix_rule = OrRule({azure_priv_name_rule, azure_qa_cloud_name_rule})")
    print("prod_selector = AndRule({azure_net_rule, prod_prefix_rule, prod_suffix_rule})")
    print("qa_selector = AndRule({azure_net_rule, qa_prefix, qa_suffix_rule})")
    print("no_recurse_selector = AndRule({azure_net_rule, azure_prefix_rule, azure_pub_name_rule})")

def actions():
    print("\n-- Actions")
    print("addAction(local_name_rule, PoolAction('local'))")
    print("addAction(arpa_rule, PoolAction('local'))")
    print("addAction(qa_selector, PoolAction('azure_qa'))")
    print("addAction(prod_selector, PoolAction('azure_prod'))")
    print("addAction(no_recurse_selector, PoolAction('local'))")
    print("addAction(typo_rule, PoolAction('typo'))")

def lua_functions():
    print("\n-- Functions")
    print("function mainentance()")
    print("    dbr:apply()")
    print("end")

def test():
    jinga_header()
    glob()
    servers()
    dynamic_blocks()
    net_mask_groups()
    suffix_match_nodes()
    regex_patterns()
    selectors()
    actions()

def main():
    glob()
    servers()
    dynamic_blocks()
    net_mask_groups()
    suffix_match_nodes()
    regex_patterns()
    selectors()
    actions()
    #lua_functions()

if __name__ == '__main__':
    sys.exit(test())
