local-data: "q031_test.mariadb.database.azure.com. 3600 CNAME q031_test.privatelink.mariadb.database.azure.com."
local-data: "q228_test.mariadb.database.azure.com. 3600 CNAME q228_test.privatelink.mariadb.database.azure.com."
local-data: "q277_test.mariadb.database.azure.com. 3600 CNAME q277_test.privatelink.mariadb.database.azure.com."
local-data: "q278bozo.mariadb.database.azure.com. 3600 CNAME q278bozo.privatelink.mariadb.database.azure.com."
local-data: "q301_abc.mariadb.database.azure.com. 3600 CNAME q301_abc.privatelink.mariadb.database.azure.com."
local-data: "q569_test.mariadb.database.azure.com. 3600 CNAME q569_test.privatelink.mariadb.database.azure.com."
local-data: "q574_test.mariadb.database.azure.com. 3600 CNAME q574_test.privatelink.mariadb.database.azure.com."
local-data: "z234_do_not_remove.mariadb.database.azure.com. 3600 CNAME z234_do_not_remove.privatelink.mariadb.database.azure.com."
