local-data: "n031_test.gremlin.cosmos.azure.com. 3600 CNAME n031_test.privatelink.gremlin.cosmos.azure.com."
local-data: "n228_test.gremlin.cosmos.azure.com. 3600 CNAME n228_test.privatelink.gremlin.cosmos.azure.com."
local-data: "n234_test.gremlin.cosmos.azure.com. 3600 CNAME n234_test.privatelink.gremlin.cosmos.azure.com."
local-data: "n277_test.gremlin.cosmos.azure.com. 3600 CNAME n277_test.privatelink.gremlin.cosmos.azure.com."
local-data: "n278_test.gremlin.cosmos.azure.com. 3600 CNAME n278_test.privatelink.gremlin.cosmos.azure.com."
local-data: "n301_test.gremlin.cosmos.azure.com. 3600 CNAME n301_test.privatelink.gremlin.cosmos.azure.com."
local-data: "n569_test.gremlin.cosmos.azure.com. 3600 CNAME n569_test.privatelink.gremlin.cosmos.azure.com."
local-data: "n574_test.gremlin.cosmos.azure.com. 3600 CNAME n574_test.privatelink.gremlin.cosmos.azure.com."
