local-data: "q031_test.cassandra.cosmos.azure.com. CNAME q031_test.privatelink.cassandra.cosmos.azure.com."
local-data: "q228_test.cassandra.cosmos.azure.com. CNAME q228_test.privatelink.cassandra.cosmos.azure.com."
local-data: "q234_test.cassandra.cosmos.azure.com. CNAME q234_test.privatelink.cassandra.cosmos.azure.com."
local-data: "q277_test.cassandra.cosmos.azure.com. CNAME q277_test.privatelink.cassandra.cosmos.azure.com."
local-data: "q278_test.cassandra.cosmos.azure.com. CNAME q278_test.privatelink.cassandra.cosmos.azure.com."
local-data: "q569_test.cassandra.cosmos.azure.com. CNAME q569_test.privatelink.cassandra.cosmos.azure.com."
local-data: "q574_test.cassandra.cosmos.azure.com. CNAME q574_test.privatelink.cassandra.cosmos.azure.com."
