local-data: "q031_test.cognitiveservices.azure.com. CNAME q031_test.privatelink.cognitiveservices.azure.com."
local-data: "q228_test.cognitiveservices.azure.com. CNAME q228_test.privatelink.cognitiveservices.azure.com."
local-data: "q234_test.cognitiveservices.azure.com. CNAME q234_test.privatelink.cognitiveservices.azure.com."
local-data: "q277_test.cognitiveservices.azure.com. CNAME q277_test.privatelink.cognitiveservices.azure.com."
local-data: "q278_test.cognitiveservices.azure.com. CNAME q278_test.privatelink.cognitiveservices.azure.com."
local-data: "q569_test.cognitiveservices.azure.com. CNAME q569_test.privatelink.cognitiveservices.azure.com."
local-data: "q574_test.cognitiveservices.azure.com. CNAME q574_test.privatelink.cognitiveservices.azure.com."
