local-data: "q031_test.token.botframework.com. CNAME q031_test.privatelink.token.botframework.com."
local-data: "q228_test.token.botframework.com. CNAME q228_test.privatelink.token.botframework.com."
local-data: "q234_test.token.botframework.com. CNAME q234_test.privatelink.token.botframework.com."
local-data: "q277_test.token.botframework.com. CNAME q277_test.privatelink.token.botframework.com."
local-data: "q278_test.token.botframework.com. CNAME q278_test.privatelink.token.botframework.com."
local-data: "q569_test.token.botframework.com. CNAME q569_test.privatelink.token.botframework.com."
local-data: "q574_test.token.botframework.com. CNAME q574_test.privatelink.token.botframework.com."
