local-data: "q031_test.purview.azure.com. CNAME q031_test.privatelink.purview.azure.com."
local-data: "q228_test.purview.azure.com. CNAME q228_test.privatelink.purview.azure.com."
local-data: "q234_test.purview.azure.com. CNAME q234_test.privatelink.purview.azure.com."
local-data: "q277_test.purview.azure.com. CNAME q277_test.privatelink.purview.azure.com."
local-data: "q278_test.purview.azure.com. CNAME q278_test.privatelink.purview.azure.com."
local-data: "q569_test.purview.azure.com. CNAME q569_test.privatelink.purview.azure.com."
local-data: "q574_test.purview.azure.com. CNAME q574_test.privatelink.purview.azure.com."
