local-data: "q031_test.table.cosmos.azure.com. CNAME q031_test.privatelink.table.cosmos.azure.com."
local-data: "q228_test.table.cosmos.azure.com. CNAME q228_test.privatelink.table.cosmos.azure.com."
local-data: "q234_test.table.cosmos.azure.com. CNAME q234_test.privatelink.table.cosmos.azure.com."
local-data: "q277_test.table.cosmos.azure.com. CNAME q277_test.privatelink.table.cosmos.azure.com."
local-data: "q278_test.table.cosmos.azure.com. CNAME q278_test.privatelink.table.cosmos.azure.com."
local-data: "q569_test.table.cosmos.azure.com. CNAME q569_test.privatelink.table.cosmos.azure.com."
local-data: "q574_test.table.cosmos.azure.com. CNAME q574_test.privatelink.table.cosmos.azure.com."
