local-data: "q031_test.monitor.azure.com. CNAME q031_test.privatelink.monitor.azure.com."
local-data: "q228_test.monitor.azure.com. CNAME q228_test.privatelink.monitor.azure.com."
local-data: "q234_test.monitor.azure.com. CNAME q234_test.privatelink.monitor.azure.com."
local-data: "q277_test.monitor.azure.com. CNAME q277_test.privatelink.monitor.azure.com."
local-data: "q278_test.monitor.azure.com. CNAME q278_test.privatelink.monitor.azure.com."
local-data: "q569_test.monitor.azure.com. CNAME q569_test.privatelink.monitor.azure.com."
