local-data: "q031_test.tip1.powerquery.microsoft.com. CNAME q031_test.privatelink.tip1.powerquery.microsoft.com."
local-data: "q228_test.tip1.powerquery.microsoft.com. CNAME q228_test.privatelink.tip1.powerquery.microsoft.com."
local-data: "q234_test.tip1.powerquery.microsoft.com. CNAME q234_test.privatelink.tip1.powerquery.microsoft.com."
local-data: "q277_test.tip1.powerquery.microsoft.com. CNAME q277_test.privatelink.tip1.powerquery.microsoft.com."
local-data: "q278_test.tip1.powerquery.microsoft.com. CNAME q278_test.privatelink.tip1.powerquery.microsoft.com."
local-data: "q569_test.tip1.powerquery.microsoft.com. CNAME q569_test.privatelink.tip1.powerquery.microsoft.com."
local-data: "q574_test.tip1.powerquery.microsoft.com. CNAME q574_test.privatelink.tip1.powerquery.microsoft.com."
