local-data: "q031_test.directline.botframework.com. CNAME q031_test.privatelink.directline.botframework.com."
local-data: "q228_test.directline.botframework.com. CNAME q228_test.privatelink.directline.botframework.com."
local-data: "q234_test.directline.botframework.com. CNAME q234_test.privatelink.directline.botframework.com."
local-data: "q277_test.directline.botframework.com. CNAME q277_test.privatelink.directline.botframework.com."
local-data: "q278_test.directline.botframework.com. CNAME q278_test.privatelink.directline.botframework.com."
local-data: "q569_test.directline.botframework.com. CNAME q569_test.privatelink.directline.botframework.com."
local-data: "q574_test.directline.botframework.com. CNAME q574_test.privatelink.directline.botframework.com."
