local-data: "q031_test.wvd.microsoft.com. CNAME q031_test.privatelink-global.wvd.microsoft.com."
local-data: "q228_test.wvd.microsoft.com. CNAME q228_test.privatelink-global.wvd.microsoft.com."
local-data: "q234_test.wvd.microsoft.com. CNAME q234_test.privatelink-global.wvd.microsoft.com."
local-data: "q277_test.wvd.microsoft.com. CNAME q277_test.privatelink-global.wvd.microsoft.com."
local-data: "q278_test.wvd.microsoft.com. CNAME q278_test.privatelink-global.wvd.microsoft.com."
local-data: "q569_test.wvd.microsoft.com. CNAME q569_test.privatelink-global.wvd.microsoft.com."
local-data: "q574_test.wvd.microsoft.com. CNAME q574_test.privatelink-global.wvd.microsoft.com."
