local-data: "q228_test.postgres.database.azure.com. CNAME q228_test.privatelink.postgres.database.azure.com."
local-data: "q234_test.postgres.database.azure.com. CNAME q234_test.privatelink.postgres.database.azure.com."
local-data: "q277_test.postgres.database.azure.com. CNAME q277_test.privatelink.postgres.database.azure.com."
local-data: "q278_test.postgres.database.azure.com. CNAME q278_test.privatelink.postgres.database.azure.com."
local-data: "q569_test.postgres.database.azure.com. CNAME q569_test.privatelink.postgres.database.azure.com."
local-data: "q574_test.postgres.database.azure.com. CNAME q574_test.privatelink.postgres.database.azure.com."
