---

- name: Update, upgrade apt packages and then reboot
  hosts: ubuntu
  become: true
  tasks:
  - name: update
    apt:
      update_cache: yes
#     update_cache_retries: 3
      autoclean: yes
      autoremove: yes
      upgrade: safe
  - name: And then reboot
    reboot:

...
