---

- hosts: all
  become: yes
  vars:
    select_crypto_backend: "cryptography"
    root_dir: "/etc/sectigo"
    data_dir: "{{ root_dir }}/{{ inventory_hostname }}"
    cert_cn: "{{ ansible_facts['fqdn'] }}"
    contact_email: russell.sutherland@utoronto.ca
    acme_dir_url: "{{ lookup('ansible.builtin.env', 'SECTIGO_ACME_URL') }}"
    account_key_name: "{{ lookup('ansible.builtin.env', 'SECTIGO_ACCT_NAME') }}"
    eab_kid: "{{ lookup('ansible.builtin.env', 'EAB_KID') }}"
    eab_key: "{{ lookup('ansible.builtin.env', 'EAB_KEY') }}"
    eab_alg: "{{ lookup('ansible.builtin.env', 'EAB_ALG') }}"

  tasks:

  - name: Make sure crypto packages are installed
    community.general.openbsd_pkg:
      name:
        - py3-cryptography--
      state: latest
    when: ansible_facts['distribution'] == 'OpenBSD'

  - name: Creates data directory
    file:
      path: "{{data_dir}}"
#      path: "{{ data_dir }}/{{ inventory_hostname }}"
      state: directory
      mode: 0755
    tags: dir

  - name: Generate account keys
    community.crypto.openssl_privatekey:
      path: "{{ root_dir }}/{{ account_key_name }}.pem"
      type: RSA
      size: 2048

  - name: Parse account keys (to ease debugging some test failures)
    community.crypto.openssl_privatekey_info:
      path: "{{ root_dir }}/{{ account_key_name }}.pem"
      return_private_key_data: true
    register: acct_priv_key

  - name: Dump acct priv key
    ansible.builtin.debug:
      var: acct_priv_key
    tags: debug

  - name: Create account with External Account Binding
    community.crypto.acme_account:
      select_crypto_backend: "{{ select_crypto_backend }}"
      account_key_src: "{{ root_dir }}/{{ account_key_name }}.pem"
      acme_version: 2
      acme_directory: "{{ acme_dir_url }}"
      state: present
      allow_creation: yes
      terms_agreed: yes
      contact: "mailto:{{ contact_email }}"
      external_account_binding:
        kid: "{{ eab_kid }}"
        alg: "{{ eab_alg }}"
        key: "{{ eab_key }}"
    register: account_created_eab

  - name: Dump EAB Acount Info
    ansible.builtin.debug:
      var: account_created_eab
    tags: debug
  
  - name: Get certificate from Sectigo CA
    ansible.builtin.include_tasks: get-cert.yml
    vars:
      certgen_title: "{{ cert_cn }} Certificate"
      acme_dir: "{{ acme_dir_url }}"
      certificate_name: "{{ cert_cn }}"
      key_type: rsa
      rsa_bits: 2048
      subject_alt_name: "DNS:{{ cert_cn }}"
      subject_alt_name_critical: no
      account_key: "{{ account_key_name }}"
      challenge: http-01
      modify_account: no
      force: yes
      remaining_days: 10
      terms_agreed: yes
      account_email: "{{ contact_email }}"
      use_csr_content: false

  - name: Store results for get cert
    set_fact:
      cert_result: "{{ get_certificate_result }}"
    tags: debug

#  - debug: var=cert_result
#  tags: debug

