---

- name: Install dnsdist on institutional caching name servers
  gather_facts: true
  hosts: dns_cache_obsd
  become: yes
  vars:
    max_clients: 10
    azure_private_names: "{{ lookup('file', 'files/json_azure_private_names.txt').splitlines() }}"

  tasks:

    - name: start by loading in some common variables
      ansible.builtin.include_vars:
        dir: vars/all
        extensions:
          - 'yaml'
          - 'yml'
          - 'json'
      tags: vars

    - name: start by loading in some variables that are OS dependent
      ansible.builtin.include_vars: "{{ item }}"
      with_first_found:
        - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yaml"
        - "{{ ansible_distribution }}.yaml"
        - default.yaml
      tags: vars

    - name: make sure dnsdist is installed for Ubuntu systems
      apt:
        name: dnsdist
        state: present
      become_method: "{{ become_method }}"
      when: ansible_facts['distribution'] == 'Ubuntu'
      tags: dnsdist-server,dnsdist

    - name: Write some files to be included for dnsdist
      ansible.builtin.copy:
        src: "files/dnsdist/{{ item }}"
        dest: "{{ dnsdist_dir }}"
        backup: true
        owner: root
        mode: 0644
      with_items:
          - access.cidr
      when: inventory_hostname in local_resolvers
      notify: Restart dnsdist
      tags: dnsdist-static-files,dnsdist

    - name: Generate and install the dnsdist.conf file
      ansible.builtin.template:
        src: "dnsdist_conf.j2"
        dest: "{{ dnsdist_dir }}/dnsdist.conf"
        backup: true
        owner: root
        group: wheel
        mode: 0660
        validate: /usr/local/bin/dnsdist --check-config --config %s
      when: inventory_hostname in local_resolvers
      notify: Restart dnsdist
      tags: dnsdist,dnsdist-conf

  handlers:

    - name: Restart dnsdist
      service:
        name: dnsdist
        state: restarted
