---

- name: Enable Duo MFA on OpenBSD
  hosts: obsd_doas
  gather_facts: true
  become: yes

  tasks:

  - name: Make sure the duo packages are installed
    openbsd_pkg:
      name:
        - login_duo
      state: latest
    tags: pkgs

  - name: Add the Duo configuration file
    ansible.builtin.copy:
      src: files/duo/login_duo.conf
      dest: /etc/login_duo.conf
      owner: sshd
      group: wheel
      mode: '0600'

  - name: Add a standard pf.conf file
    template:
      src: pf_conf.jinga
      dest: /etc/pf.conf
      owner: root
      group: wheel
      mode: 0600
    notify:
      - reload pf.conf
    tags: pf

  - name: Add the correct config to the end of the sshd_config file
    ansible.builtin.blockinfile:
      path: /etc/ssh/sshd_config
      block: |
        
        # Duo MFA for ssh
        Match Group duo
            ForceCommand /usr/local/sbin/login_duo
            PermitTunnel no
            AllowTcpForwarding no
      insertafter: "EOF"
      state: present
    notify:
      - Restart sshd

  - name: Add a group duo
    ansible.builtin.group:
      name: duo
      state: present

  - name: Add a list of users
    ansible.builtin.user:
      name: uu7
      append: yes
      comment: "piekarz1,Adam Piekarzewski"
      generate_ssh_key: true
      groups:
        - duo
        - wheel
      shell: /usr/local/bin/bash

  - name: Add a list of users
    ansible.builtin.user:
      name: jchan
      append: yes
      comment: "chanjas5,Jason Chan"
      generate_ssh_key: true
      groups:
        - duo
        - wheel
      password: "$2b$10$MfzZezn6neX4RucpgydFsu8I1kGHiLj7ogyPnY5ST2IXvRILvWpnm"
      shell: /usr/local/bin/bash

  - name: Add a list of users
    ansible.builtin.user:
      name: deniz
      append: yes
      comment: "piekarz1,Adam Piekarzewski"
      generate_ssh_key: true
      groups:
        - duo
        - wheel
      shell: /usr/local/bin/bash

  - name: Add a list of users
    ansible.builtin.user:
      name: russ
      append: yes
      comment: "sutherl4,Russell Sutherland"
      generate_ssh_key: true
      groups:
        - duo
        - wheel

  handlers:
    - name: Restart sshd
      ansible.builtin.service:
        name: sshd
        state: restarted

    - name: reload pf.conf
      command: pfctl -f /etc/pf.conf
